import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav className="nav">
          <p className="logo">{process.env.NEXT_PUBLIC_WEBSITE_NAME}</p>
          <ul>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/cuet-ug">CUET UG</Link></li>
            <li><Link href="/upsc">UPSC</Link></li>
          </ul>
          <div className="btnWrapper">
            <button className="heroBtn">Login</button>
            <button className="heroBtn">More Info</button>
          </div>
          <div className="btnWrapper2">
            <Link href={"/"}><button className="heroBtn">Home</button></Link>
          </div>
        </nav>
        {children}
        <footer className="footer">
          Copyright 2025 {process.env.NEXT_PUBLIC_WEBSITE_NAME}
        </footer>
      </body>
    </html>
  );
}
